import Head from 'next/head'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <script async src="https://apis.google.com/js/api.js"></script>
      </Head>
      <body>{children}</body>
    </html>
  );
}
