import Link from 'next/link';
import './globals.css'
import DataProvider from './contextProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <DataProvider>
          <header className=' flex flex-row bg-gray-400 pb-2 pt-4'>
            <div className='px-8'>
              <Link href='/'>
                <h1>Home</h1>
              </Link>
            </div>
            <div className='px-8'>
              <Link href='/map'>
                <button>Data Map</button>
              </Link>
            </div>
            <div className='px-8'>
              <Link href='/table'>
                <button>Data Table</button>
              </Link>
            </div>
            <div className='px-8'>
              <Link href='/chart'>
                <button>Data Chart</button>
              </Link>
            </div>
          </header>
          {children}
        </DataProvider>
      </body>
    </html>
  );
}
