import Link from 'next/link';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='flex flex-row pt-4 pb-2 bg-blue-400'>
          <div className='px-8'>
            <Link href="/">
              <h1>Home</h1>
            </Link>
          </div>
          <div className="px-8">
            <Link href="/map">
              <button>Data Map</button>
            </Link>
          </div>
          <div className="px-8">
            <Link href="/table">
              <button>Data Table</button>
            </Link>
          </div>
          <div className="px-8">
            <Link href="/chart">
              <button>Data Chart</button>
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
